# -*- coding: utf-8 -*-
"""OpencV_Basics1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1D-HdhVefDEACZwNzxJrjUA3b1JmYO8KN
"""

import cv2 as cv

#reading an image
img=cv.imread('cat.jpg')

from google.colab.patches import cv2_imshow
cv2_imshow(img)

#reading videos
capture=cv.VideoCapture('dog.mp4')

while True:
  isTrue, frame=capture.read()
  cv2_imshow(frame)
  
#if 'd' is pressed break out of the while
  if cv.waitKey(20) & 0xFF==ord('d'):
    break

capture.release()
cv.destroyAllWindows()

#Rescaling an image
img=cv.imread('cat_large.jpg')
cv2_imshow(img)

def rescaleFrame(frame,scale=0.5):
  #images, videos, live videos
  width=int(frame.shape[1] * scale)
  height=int(frame.shape[0] * scale)
  dimensions=(width,height)

  return cv.resize(frame,  dimensions, interpolation=cv.INTER_AREA)

rescaled_img=rescaleFrame(img)
cv2_imshow(rescaled_img)

def changeRes(width, height):
  #change resolution of a live video
  capture.set(3,width)
  capture.set(4,height)